trigger:
  - master

pool:
  vmImage: 'windows-latest'

jobs:
  - job: test
    displayName: Unit tests
    steps:
      - powershell:
          Install-Module Pester -Scope CurrentUser -Force
        name: test_deps
        displayName: Install tests' dependencies
      - powershell: |
          Invoke-Pester test/EnvVar.Tests.ps1
        name: test_body
        displayName: Run tests
  - deployment: publish
    displayName: Publish to PowerShell Gallery
    dependsOn: [test]
    condition: "eq(succeeded(), failed())" # temporary
    environment: PSGallery
    strategy:
      runOnce:
        deploy:
          steps: []
